version: "3.9"

services:
  web:
    build: .
    container_name: flyhub_be
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:6.2"
    container_name: redis
    ports:
      - "6379:6379"
